name: build

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 10 15 * *"
  workflow_dispatch:

env:
  REGISTRY: docker.io
  IMAGE_NAME: ssh-test

jobs:
  set-dists:
    runs-on: ubuntu-latest
    outputs:
      dists: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - id: set-matrix
        run: |
          content=$(jq -c . dist.json)
          echo matrix=${content} >>$GITHUB_OUTPUT
          echo ${content}
  build:
    needs: set-dists
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.set-dists.outputs.dists) }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/build-push-action@v3
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          build-args: |
            dist=${{ matrix.dist }}
            ver=${{ matrix.ver }}
          tags: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ matrix.dist }}.${{ matrix.ver }}
